''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'BIGNUM.BAS  08/22/1992  FOR IBM PC  AND COMPATIBLES
' FROM OCT CREATIVE COMPUTING BY  JERRY CRAVEA
' MADE TO RUN  ON CP/M 2.2 MBASIC BY T MCCORMICK  05/82
' MADE TO RUN ON QBASIC v1.00 BY P J LUCAS 08/22/1992
'''''''''''


GOTO 50
  'SAVE "BIGNUM3.BAS", A: STOP
50 CLS
   PRINT TAB(20); "   B I G    N U M B E R S   G A M E"
   PRINT : PRINT "Please Enter A 4-digit "; : RANDOMIZE
   PRINT
    CLEAR 500
    DIM W$(101), W1$(10), W2$(10), W3$(8), W4$(34), W5$(21), W6$(36), W7$(74)
    FOR LL = 1 TO 10: READ W1$(LL): NEXT LL
    FOR II = 1 TO 10: READ W2$(II): NEXT II
    FOR OO = 1 TO 8: READ W3$(OO): NEXT OO
    FOR QQ = 1 TO 34: READ W4$(QQ): NEXT QQ
    FOR EE = 1 TO 21: READ W5$(EE): NEXT EE
    FOR GG = 1 TO 36: READ W6$(GG): NEXT GG
    FOR UU = 1 TO 74: READ W7$(UU): NEXT UU
     DATA "ZERO","ONE","TWO","THREE","FOUR","FIVE","SIX","SEVEN"
     DATA "EIGHT","NINE"
     DATA "TEN","ELEVEN","TWELVE","THIRTEEN","FOURTEEN","FIFTEEN"
     DATA "SIXTEEN","SEVENTEEN","EIGHTEEN","NINTEEN"
     IF D$ = "0" THEN 8800
     DATA "TWENTY ","THIRTY ","FOURTY ","FIFTY ","SIXTY ","SEVENTY "
     DATA "EIGHTY ","NINETY "
     DATA "HUNDRED","THOUSAND","MILLION","BILLION","TRILLION","QUADRILLION"
     DATA "QUINTILLION","SEXTILLION","SEPTILLION","OCTILLION","NONILLION"
     DATA "DECILLION","UNDECILLION","DUODECILLION","TREDECILLION"
     DATA "QUATTUORDECILLION","QUINDECILLION","SEXDECILLION"
     DATA "SEPTENDECILLION","OCTODECILLION","NOVEMDECILLION","VIGINTILLION"
     DATA "VIGINTIUNTILLION","VIGINTIDUOTILLION","VIGINTITRETILLION"
     DATA "VIGINTIQUATTOURTILLION","VIGINTIQUINTILLION","VIGINTISEXTILLION"
     DATA "VIGINTISEPTILLION","VIGINTIOCTILLION","VIGINTINONILLION"
     DATA "TRIGINTATILLION","TRIGINTAUNTILLION","TRIGINTADUOTILLION"
     DATA "FIRST","SECOND","THIRD","FOURTH","FIFTH","SIXTH","SEVENTH"
     DATA "EIGHTH","NINTH","TENTH","ELEVENTH","TWELFTH","THRITEENTH"
     DATA "FOURTEENTH","FIFTEENTH","SIXTEENTH","SEVENTEENTH","EIGHTEENTH"
     DATA "NINTEENTH","TWENTIETH","NEXT "
     C = 0
     I = 0
     PRINT
     PRINT "HI THERE! MY NAME IS BIG NUMBERS, WHAT IS YOUR NAME";
     PRINT "                  (KEEP IT CLEAN)"
3600 INPUT A1$
     J = LEN(A1$)
     IF J <= 25 THEN 4900
     IF I <> 0 THEN 4700
     PRINT
     PRINT "SORRY "; A1$; ","
     PRINT "BUT I GET TIRED EASILY SAYING LONG NAMES."
     PRINT "LONG NUMBERS ARE MY THING, YOU KNOW"
     PRINT "PLEASE RETYPE YOUR NAME NOW AND LIMIT TO 25 SPACES OR LESS."
     I = 1
     GOTO 3600
4700 A1$ = MID$(A1$, 1, 25)
     GOTO 5100
4900 IF I = 0 THEN 5100
     PRINT "WHEW, THANK YOU "; A1$; "! THATS MUCH BETTER."
5100 PRINT
     PRINT "NOW "; A1$; ",DO YOU WANT SOME INSTRUCTIONS"
     PRINT "ON WHAT TO DO (YES/NO)";
     INPUT A$
     IF MID$(A$, 1, 1) = "N" THEN 6500
     IF MID$(A$, 1, 1) = "n" THEN 6500
     IF MID$(A$, 1, 1) <> "Y" THEN 5700
     IF MID$(A$, 1, 1) <> "y" THEN 5700
5700 PRINT
     PRINT "I CAN TEACH YOU HOW TO SAY BIG NUMBERS, "; A1$; "."
     PRINT "TYPE IN ANY POSITIVE WHOLE NUMBER AND I WILL PRINT  THE WORDS"
     PRINT "TO USE TO SAY THAT NUMBER IN ENGLISH YOU MAY USE COMMAS TO"
     PRINT "SEPARATE GROUPS OF THREE DIGITS IF  YOU WISH BUT YOU DONT HAVE"
     PRINT "TO FOR EXAMPLE, 1093 & 1,093 ARE THE SAME NUMBER TO ME"
     PRINT "ONLY THE 10 DIGITS (0-9) AND COMMAS (,) ARE ALLOWED IN THE"
     PRINT "NUMBERS YOU TYPE IN. WHEN YOU WISH TO STOP, TYPE END OR QUIT"
6500 PRINT
     C = C + 1
     IF C <= 21 THEN 6900
     C = 21
6900 PRINT " OK, "; A1$; ". ENTER YOUR "; W5$(C); " NUMBER NOW"
     PRINT "TYPE (QUIT OR END) WHEN YOUR FINISHED."
7000 INPUT I$
     IF MID$(I$, 1, 3) = "END" THEN 22000
     IF MID$(I$, 1, 3) = "end" THEN 22000
     IF MID$(I$, 1, 4) = "QUIT" THEN 22000
     IF MID$(I$, 1, 4) = "quit" THEN 22000
     L = LEN(I$)
     N = 0
     G = 0
     Z = 1
     FOR J = 1 TO L
     D$ = MID$(I$, J, 1)
     IF D$ = "," THEN 8800
     IF D$ = " " THEN 8800
     IF D$ < "0" OR D$ > "9" THEN 9900
     ON Z GOTO 8300, 8500
8300 IF D$ = "0" THEN 8800
     Z = 2
8500 N = N + 1
     IF N > 101 THEN 17600
     W$(N) = D$
8800 NEXT J
     IF N > 0 GOTO 9200
     N = 1
     W$(N) = "0"
9200 IF N <> 101 THEN 10300
     IF W$(1) <> "1" THEN 17600
     FOR J = 2 TO N
     IF W$(J) <> "0" THEN 17600
     NEXT J
     G = 1
      GOTO 10300
9900 PRINT "SORRY BUT THE NUMBER YOU ENTER MUST CONTAIN ONLY"
      PRINT "DIGITS (0-9) AND COMMAS - NO OTHER CHARACTERS"
      PRINT "PLEASE REENTER YOUR "; W5$(C); " NUMBER CORRECTLY NOW"
       GOTO 7000
10300 IF N <= 9 THEN 10700
      I = INT((RND(0) * 36) + 1)
      J = INT((RND(0) * 74) + 1)
      PRINT W6$(I); " "; A1$; ", THAT WAS "; W7$(J); " NUMBER"
10700 N1 = INT((N + 2) / 3)
      N2 = ((N1 * 3) + 1) - N
      PRINT "THE NUMBER ";
      J = 11
      ON N2 GOTO 11600, 11400, 11200
11200 PRINT " ";
      J = J + 1
11400 PRINT " ";
      J = J + 1
11600 FOR I = 1 TO N
      ON N2 GOTO 11800, 11800, 11800, 12000
11800 PRINT W$(I);
       GOTO 12100
12000 PRINT ",";
12100 J = J + 1
      N2 = N2 + 1
      IF N2 <= 4 THEN 12500
      N2 = 1
12500 IF J <= 78 THEN 13000
      PRINT
      PRINT TAB(11);
      J = 11
       GOTO 11800
13000 IF N2 = 1 THEN 11800
      NEXT I
      PRINT
      PRINT TAB(5); "IS SPOKEN IN ENGLISH AS: "
      IF G = 0 THEN 13800
      PRINT "TAB(11); "; ONE; GOOGOL; ""
      G = 0
       GOTO 6500
13800 N2 = ((N1 * 3) + 1) - N
      PRINT TAB(11);
      F1 = 1
      F2 = 0
      FOR I = 1 TO N
      D = VAL(W$(I))
      ON N2 GOTO 14500, 15000, 15600
14500 F2 = F2 + D
      IF D = 0 THEN 17000
      PRINT W1$(D + 1); : PRINT " ";
      PRINT W4$(1); : PRINT " ";
       GOTO 17000
15000 F2 = F2 + D
      ON D + 1 GOTO 17000, 15200, 15400, 15400, 15400, 15400, 15400, 15400, 15400, 15400
15200 F1 = 2
       GOTO 17000
15400 PRINT W3$(D - 1);
       GOTO 17000
15600 F2 = F2 + D
      ON F1 GOTO 15800, 16300
15800 IF N = 1 THEN 16100
      IF F2 = 0 THEN 16700
      IF D = 0 THEN 16400
16100 PRINT W1$(D + 1); : PRINT " ";
       GOTO 16400
16300 PRINT W2$(D + 1); : PRINT " ";
16400 IF N1 <= 1 THEN 17000
      PRINT W4$(N1)
      PRINT TAB(11);
16700 N1 = N1 - 1
      F1 = 1
      F2 = 0
17000 N2 = N2 + 1
      IF N2 <> 4 THEN 17300
      N2 = 1
17300 NEXT I
      PRINT
       GOTO 6500
17600 PRINT
      PRINT "WELL "; A1$; " THAT NUMBER IS BIGGER THAN A GOOGOL(1FOLLOWED"
      PRINT "BY 100 ZEROS). BEFORE I TELL YOU HOW TO SAY IT, YOU MUST"
      PRINT "FIRST SHOW YOURSELF WORTHY. TAKE A PENCIL AND SOME PAPER"
      PRINT "AND WRITE DOWN ALL THE DIGITS IN A GOOGOLPLEX. A GOOGOLPLEX"
      PRINT "IS 1 FOLLOWED BY A GOOGOL NUMBER OF ZEROS WHEN YOU HAVE"
      PRINT "WRITTEN ALL THE DIGITS IN A GOOGOLPLEX DOWN ON PAPER COME"
      PRINT "AND TYPE THEM IN FOR ME AND  THEN  I WILL KNOW YOU ARE"
      PRINT "WORTHY TO SPEAK NUMBERS LARGER THAN A GOOGOL"
      PRINT "GOOD BYE FOR NOW"
      DATA "AHA","BINGO","BOY","BOY OH BOY","BRAVO","EUREKA","GAD ZOOKS"
      DATA "GOLLY","GOSH","HEY","HEY THERE","HO HO","HOORAY","MAMA MIA","MAN"
      DATA "OH BOY","OH HO HO HO","OH ME","OH ME OH MY","OH MY","OHO","OH WOW"
      DATA "OK","O SOL O MI O","RIGHT ON","WHOOPIE","WILD","WOW","YE GADS"
      DATA "YES","YIKES","YIPES","YOW","YOWIE","ZINGO","ZOWIE"
      DATA "AN AMPLE","AN AUGUST","A BIG","A BRAWNY","A CAPACIOUS"
      DATA "A COMPREHENSIVE","A COLOSSAL","AN ELEPHANTE","AN ENORMOUS"
      DATA "AN EXTENSIVE","A GIGANTIC","A GORGEOUS","A GRAND","A GREAT"
      DATA "A HUGE","A HUMONGOUS","AN IMMENSE","A LARGE","A MAGNANIMOUS"
      DATA "A MAJESTIC","A MASSIVE","A MIGHTY","A MONSTROUS","A MUSCULAR"
      DATA "AN OSTENTATIOUS","A POMPOUS","A POWERFUL","A PRINCELY"
      DATA "A PRODIGIOUS","A REGAL","A SIGNIF ICANT","A SOPHISTICATED"
      DATA "A SPACIOUS","A SPLENDID","A STUPENDOUS","A SUPERB","A VAST","A WIDE"
      DATA "NOT YOUR AVERAGE","NOT YOUR COMMON","NOT YOUR COMMANPLACE","
      DATA "NOT A CRAMPED","NOT A DWARF OF A","NOT A ELEMENTARY"
      DATA "NOT YOUR EVERDAY","NOT A FEEBLE","NOT A FLIMSY","NOT A HUMBLE"
      DATA "NOT A HUMDRUM","NOT A INCHOATE","NOT AN INSIGNIF ICENT"
      DATA "NOT A LITTLE","NOT A MEAGER","NOT A MEEK"
      DATA "NOT A MERE WISP OF A","NOT A MINUTE","NOT A MODEST"
      DATA "NOT A OBSCURE","NOT YOUR ORDINARY","NOT A PALTRY"
      DATA "NOT A PETTY","NOT A PIGMY OF A","NOT A PUERILE","NOT A PUNY"
      DATA "NOT A SCANTY","NOT TO SHABBY OF A","NOT A SHALLOW"
      DATA "NOT A SIMPLE","NOT A SMALL","NOT A TINY","NOT A TRIF LING"
      DATA "NOT A TRIVIAL","NOT A UNDERSIZED","NOT AN UNNOTICEABLE"
      END
22000 CLS
      SYSTEM

